### ISSUE TITLE
Additional Blog Hosting Provider

### ISSUE THREAD

**Issue by dmuth** [bradleytaunt/blog-anonymously#4]
I would also like to suggest listing Medium as a blog hosting provider.  The interface is simple and clean, and their Google pagerank is astonishingly highly.  Case in point, [one of my blog posts there](https://medium.com/@dmuth/ssh-at-scale-cas-and-principals-b27edca3a5d) somehow outranks both Facebook and Reddit for a specific search:

![image](https://user-images.githubusercontent.com/374060/87202611-e5a3f300-c2ce-11ea-9f9e-3af6e7f9fb96.png)

(And while there's an argument for that literal phrase not being in the Facebook post, given their size, I'd expect their PageRank to be second only to the likes of Google themselves and Reddit.)

As a related note (but probably not deserving of a separate issue here), I would recommend that tags be used on platforms that support them, such as Tumblr.  Because when something is tagged, it shows up in a public list of posts with that tag.  For example, if I tag something "cheetah", it will show up on [Tumblr's cheetah tag page](https://www.tumblr.com/search/cheetah), which is very likely crawled by Google (as tags from other posts link to it), which is a great way to get that URL into the Google Index.

**Comment by bradleytaunt** [comment]
Although I'm open to adding new blogging platforms, I can't in good conscience recommend Medium. They treat readers/users very poorly by implementing shady UX practices - which defeats the whole purpose of running a decent blogging website :smiley_cat: 

Extra reading for further reasoning: https://medium.com/@nikitonsky/medium-is-a-poor-choice-for-blogging-bb0048d19133

**Comment by dmuth** [comment]
Thanks for sharing that.  It looks like Medium no longer does two of the practices outlined there (the full screen ad and the bar that hovers at the top of the screen), but of the other things mentioned are concerning, especially not respecting the Do Not Track header.  That's plenty enough of a reason to not list them.
